name: Image Building

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ "main" ]

jobs:

  Debian:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile.slim --tag my-image-name:$(date +%s)
  
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile.alpine --tag my-image-name:$(date +%s)

